misc:
  num_workers: 8
  ckpt_path: models/best.ckpt
  log_dir: results

data:
  audio_dirs:
    - data/dev/fan
    - data/dev/pump
    - data/dev/slider
    - data/dev/valve
    - data/dev/ToyCar
    - data/dev/ToyConveyor
  train_split: 0.8
  fast_dev_run: False

transform:
  type: mel_spectrogram
  params:
  # audio params
    sr: 16000
    duration: 10
  # spectrogram params
    n_fft: 1024
    hop_length: 512
    # mel spectrogram params
    n_mels: 64
    # mfcc params
    n_mfcc: 40

model:
  type: baseline_ae
  layers:
    hidden_size: 128
    latent_size: 8

train:
  seed: 42
  epochs: 10
  batch_size: 32
  lr: 0.001
