[tool.poetry]
name = "diffusion-audio-anomaly"
version = "0.1.0"
description = ""
authors = ["Balazs G. Horvath <bghorvath@pm.me>"]
readme = "README.md"
packages = [{include = "diffusion_audio_anomaly"}]

[tool.poetry.dependencies]
python = ">=3.11 <3.12"
numpy = "^1.24.3"
pandas = "^2.0.1"
ipykernel = "^6.23.0"
scikit-learn = "^1.2.2"
librosa = "^0.10.0.post2"
matplotlib = "^3.7.1"
pytest = "^7.3.1"
pre-commit = "^3.3.1"
dvc = "^2.56.0"
dvc-ssh = "^2.22.1"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
